#!/usr/bin/env node
'use strict'

const { argv } = require('yargs')
const { spawn } = require('child_process')

const cmd = argv.i ? 'npm install' : `npm run ${argv.s}`

console.log(cmd)

const options = { stdio: 'inherit', cwd: 'client', shell: true }
spawn(cmd, [], options)
