version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - run: npm install
      - run:
          name: Install SPA client dependencies
          working_directory: ./client
          command: npm install

      - run: npm run build

      - run:
          name: Build Docker image
          command: docker build -t appliedblockchain/b-explorer . --build-arg="NPM_TOKEN=$PRIVATE_NPM_TOKEN"
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
            docker push appliedblockchain/b-explorer

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: org-global
