version: 2
jobs:
  build-client:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - run:
          working_directory: ./client
          command: npm i && npm run build

      - persist_to_workspace:
          root: client
          paths:
            - build

workflows:
  version: 2
  main:
    jobs:
      - build-client
