version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - setup_remote_docker
      - checkout

      - run: npm install
      - run:
          working_directory: ./client
          command: npm install

      - run: npm run build

      - run: docker build -t appliedblockchain/b-explorer .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
            docker push appliedblockchain/b-explorer

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: org-global
